---
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---
TITLE by Rodrigo P Maruyama
========================================================

# ROCR

```{r echo = FALSE, eval = TRUE, warning = FALSE, 'set wd'}
setwd("D://Documents/ead/Udacity/dsNanodegree/dataAnalysisR/project/")
```

## Packages

```{r echo = FALSE, eval = FALSE, warning = FALSE, 'install packages'}
install.packages('randomForest', dependencies = TRUE)
install.packages('ROCR', dependencies = TRUE)
```

## Libraries 

```{r echo = TRUE, eval = TRUE, warning = FALSE, 'lilbrary'}
library(ROCR)
library(randomForest)
```

## Loading Dataset

```{r echo = TRUE, eval = TRUE, warning = FALSE, 'load dataset'}
# Load the Data
wdf <- read.csv('data/wineQualityWhites.csv')
```


## Removing Outliers

```{r echo = FALSE, eval = FALSE, warning = FALSE, 'outliers IQR'}

# Find the outliers based in the 1.5*IQR value
outliers <- data.frame()
   for (f in names(wdf[2, -12])) {
  q1 <- as.numeric(quantile(wdf[, f], 0.25))
  q3 <- as.numeric(quantile(wdf[, f], 0.75))
  step <- 1.5*(q3 - q1)
  outliers <- rbind(outliers, 
    subset(wdf, (wdf[, f] <= (q1 - step)) | (wdf[, f] >= (q3 + step))))
   }

# Just getting the outliers in more than one feature
outliers <- outliers[duplicated(outliers), ]
dim(outliers)

# Removing the outliers from the dataset
wdf.outliers <- anti_join(wdf, outliers)
wdf.outliers$X <- NULL
```


## Creating Training and Test Datasets for Outliers

```{r echo = TRUE, eval = TRUE, warning = FALSE, 'removing outliers'}

wdf.outliers$quality <- as.factor(wdf.outliers$quality)

# Creating Train.outliers and Test.outliers datasets
set.seed(13)
samp <- sample(nrow(wdf.outliers), 0.4 * nrow(wdf.outliers))
train.outliers <- wdf.outliers[samp, ]
test.outliers <- wdf.outliers[-samp, ]
```


## Random Forest Model

```{r echo = TRUE, eval = TRUE, warning = FALSE, 'Random Forest'}

# Random Forest Raw
model <- randomForest(quality ~ . - quality, data = train.outliers)
rf.pred <- predict(model, newdata = test.outliers[, -12])
rf.pred.prob <- predict(model, newdata = test.outliers[, -12], type = 'prob')
rf.pred <- as.numeric(rf.pred)
test.outliers$quality <- as.numeric(test.outliers$quality)

s <- length(rf.pred)
a <- 0
bin.pred <- c(1:2819)
while (a < s) {
    a <- a + 1
    if (rf.pred[a] == test.outliers$quality[a]) {
      bin.pred[a] <- 1
      print(paste('TRUE', a, rf.pred[a], test.outliers$quality[a], sep = '--'))
    } else {
      bin.pred[a] <- 0
      print(paste('FALSE', a, rf.pred[a], test.outliers$quality[a], sep = '--'))
    }
}

pred <- prediction(rf.pred, test.outliers$quality)
perf <- performance(pred,"tpr","fpr")
plot(perf)

```


